Repository brettcannon/microvenv, pull requests merged in 2023-03, with the labels that each got.

#17 Manage the release notes via GitHub Releases
  .github/release.yml
  .github/workflows/pr-labels.yml
  pyproject.toml
Labels: impact-project

#19 Add a `build` session to nox
  .github/workflows/build.yml
  noxfile.py
Labels: impact-project

#20 Make sure the file is small enough to pass in via `-c`
  README.md
  microvenv.py
  test_microvenv.py
Labels: impact-project

#21 Set up some basic VS Code configurations
  .vscode/extensions.json
  .vscode/settings.json
Labels: impact-project

#22 Make the paths in the `command` field for `pyvenv.cfg` use absolute, resolved paths
  microvenv.py
  test_microvenv.py
Labels: impact-feature

#24 Match path resolution in `pyvenv.cfg`
  microvenv.py
  pyproject.toml
  test_microvenv.py
Labels: impact-bug

#25 Simplify code around `sys._base_executable`
  microvenv.py
Labels: impact-project

#26 Add a public API via the `create()` function
  README.md
  microvenv.py
  pyproject.toml
  test_microvenv.py
Labels: impact-feature

#28 Make the creation of the `lib64` symlink more robust
  microvenv.py
  test_microvenv.py
Labels: impact-bug

#29 Simplify `pyvenv.cfg` parsing in the test suite
  test_microvenv.py
Labels: impact-project

#30 Fix documentation type hint for `create()`
  README.md
Labels: impact-bug

#31 Add a missing `assert` and fix some typos
  test_microvenv.py
Labels: impact-project

#32 Move to `hatchling` for builds
  .github/workflows/build.yml
  noxfile.py
  pyproject.toml
Labels: impact-feature

#33 Make the `lib64` symlink relative
  microvenv.py
  test_microvenv.py
Labels: impact-bug

#38 Add tests for the CLI
  test_microvenv.py
Labels: impact-project

#36 Use argparse to parse args
  microvenv.py
Labels: impact-project
