Repository brettcannon/microvenv, pull requests merged in 2023-10, with the labels that each got.

#55 Add support for Windows (except for `create()`)
  .github/workflows/ci.yml
  docs/api.rst
  docs/cli.rst
  microvenv/__init__.py
  microvenv/__init__.pyi
  microvenv/_create.pyi
  noxfile.py
  tests/test_cli.py
  tests/test_create.py
Labels: impact-feature

#57 Prevent `__main__.py` from attempting to execute on Windows.
  .readthedocs.yml
  microvenv/__main__.py
  pyproject.toml
Labels: impact-bug

#58 Get mypy passing under Windows
  .github/workflows/ci.yml
  microvenv/__main__.py
  microvenv/__main__.pyi
  microvenv/_create.pyi
  pyproject.toml
  tests/conftest.py
Labels: impact-breaking

#60 Fix documented invocation
  README.md
Labels: documentation, impact-bug
